### ISSUE TITLE
Fatal Exception trying to open camera

### ISSUE THREAD

**Issue by Iiiggs** [MicroVision-Inc/Lidar3DViewer#3]
Error from LogCat:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setPreviewCallback(android.hardware.Camera$PreviewCallback)' on a null object reference

**Comment by chaohub** [comment]
This is fixed in commit 53db1e9eb23c61fff15648378eba60b3730a5d17
